[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cda1e07d65cd47bc36360af2e3e891e5ba981714"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "98a03f2ad738b7cf61c32ce8070464d55a6d543d6b557d08db284a9c0d575bd5"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.4.1+13/rr.v5.4.1.x86_64-linux-gnu-cxx03.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24f3eb6277df1f22a6de3755306d033449697322"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "f039ed1af1b4cf64cfb9af09e7e24a2466b416f8af9da31cc1c51b8db9b48b4f"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.4.1+13/rr.v5.4.1.x86_64-linux-gnu-cxx11.tar.gz"
