[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55de5c9131a6931f5f3982d0dc52e0d89f5281db"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "230835ab9bd840e707663f9eb5cf58e4c809fe34eaf98078ca59c55a1b9032ec"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.4.1+10/rr.v5.4.1.x86_64-linux-gnu-cxx03.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58eee54fa1fd4745c1c94c8e14597ebe2cbeafd8"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "612cbdd85fe4afc750b2cc27c64083c41a2a35638eddbab9d59a3167d5c5ea0b"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.4.1+10/rr.v5.4.1.x86_64-linux-gnu-cxx11.tar.gz"
