[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbc05812f225e878c504fdf9a5a923ce9f1b5990"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "d59c1074807eefa215c5e0b2c91867afdc01509075a1a82e0e552bc7d862b66f"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.3.1+1/rr.v5.3.1.x86_64-linux-gnu-cxx11.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adabfe31c929330dabaf3bef223a38afa1966666"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "12251c2cd0d4ac4f459c5ba95ca690aa5faaba9971e4f48ae3b0549f95417054"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.3.1+1/rr.v5.3.1.x86_64-linux-gnu-cxx03.tar.gz"
