[[rr]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a21427a219ca81a5801f233d0f53aee1147c3667"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "6fcf7fd0dc3926bf39479fa494dd44468cfcc0c6590004c68d54d9834b2e56f8"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.8.0+0/rr.v5.8.0.aarch64-linux-gnu-cxx03.tar.gz"
[[rr]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a13b6b49e9ffc8e9d8231e177829f12c5b600ea"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "6c90270db0d44148411931222320b37a5d636c934c8c2e49836289086f666bad"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.8.0+0/rr.v5.8.0.aarch64-linux-gnu-cxx11.tar.gz"
[[rr]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e40b67aa086f06f9117778b50382bbeb2526af3"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "a81dc25852535b21706cb4462eb80b890ed2fec3e1fce7e562db5cdb6bdb31fc"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.8.0+0/rr.v5.8.0.i686-linux-gnu-cxx03.tar.gz"
[[rr]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38710d3107844bdbd6d64dd375bc7cc94e38a6fd"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "e9ddbf155210ef4d1524da839acb4e3aabcdb35239e77df4a150d2d4b840fa00"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.8.0+0/rr.v5.8.0.i686-linux-gnu-cxx11.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89350d6a979f12f76123ce02045f35f3b21b5b03"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "e7f7a97c3c10ab63a3b9e301d6929c0931f9e2a991f50566884373f43f1a9246"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.8.0+0/rr.v5.8.0.x86_64-linux-gnu-cxx03.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19dfdb04d199a704a12c203a6fdcf95b4872bef1"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "a64ca13355a6157dc4895d34d0e26a3edc2ab0a50b7b31d8d5ecf04005583582"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.8.0+0/rr.v5.8.0.x86_64-linux-gnu-cxx11.tar.gz"
