[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc98b6ddf5c74153ce170c28a8e86b628881f31b"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "f6332ffdd69d880af84ee4d5cce33c1adec0ed38274b6f66a692dd22bf587ef4"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.3.1+0/rr.v5.3.1.x86_64-linux-gnu-cxx11.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3e903913aeb4cad6b26078cd78e6b15986170cf"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "713091e485536f8f0ae78322c42fe825fae529f5a582678acb2758fec8690931"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.3.1+0/rr.v5.3.1.x86_64-linux-gnu-cxx03.tar.gz"
