[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ff525ffd44caeb32652bb85303b437436e839f1"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "390379214aa5fbd4717bbf7034665166bb64dbd16c4f7476d3f3f6f232b6fa21"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.4.1+2/rr.v5.4.1.x86_64-linux-gnu-cxx03.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36cde7060ef3b1e271ce66ac83ef7c4861e6803d"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "7c289cfbde53cf057c73cb6f9a07b58aed3613adfab004117efb77060c245b46"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.4.1+2/rr.v5.4.1.x86_64-linux-gnu-cxx11.tar.gz"
