[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6d7ae5f4add394abb1318b0fa80f8a52ccba5af"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "374a048c6959e1dd70ded1fdb86c5ae3439ed6c060a8fb9c528c46310a3e594d"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.4.1+9/rr.v5.4.1.x86_64-linux-gnu-cxx03.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "361975a43b8c0a5d7df4a00607fc0c4be73d2f91"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "52720430140f773351a040b84f96b12f89b47497480148d6e6ae6ec2af31ff16"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.4.1+9/rr.v5.4.1.x86_64-linux-gnu-cxx11.tar.gz"
