[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4dc70bead0bb04c1e56a38b806ee3f6816aca23"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "4691cd0c6828b2b3bf74933fe32abf2c531cdcdb5c1d92f25cc4b1a2d3fc89c6"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.3.2+0/rr.v5.3.2.x86_64-linux-gnu-cxx03.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a14b50f62fa0979a89c7df21244094f3320ffbda"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "98023e0fb6a8531c7570c93f65eb1a7d88dfe5d5a18f639cc473c02051cad635"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.3.2+0/rr.v5.3.2.x86_64-linux-gnu-cxx11.tar.gz"
