[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e35c7daf45e8dc6f0c3136c5a63592c923cf8cc4"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "5cba657ab3d0ffc5a6f4214e7f1d42a9c3f6e52bfc5d5c4d3c22723f83e696cf"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.4.1+3/rr.v5.4.1.x86_64-linux-gnu-cxx03.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b94f50c73e96dbad8959b0cccdba43bbe5770a54"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "648510629e846237fd8d881bef283df17e2b0b0b50d519382dae2c94c4e2b495"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.4.1+3/rr.v5.4.1.x86_64-linux-gnu-cxx11.tar.gz"
