[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eae2626857c0de3145614bce6e30dfa1b52898ec"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "12f6b94dac4ae4f2799c6ce65869c216dd81052f102bb37f4fd0827016987b95"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.3.1+4/rr.v5.3.1.x86_64-linux-gnu-cxx11.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8debde65e81a29449de0f33322fee45fbde600c3"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "b9b0ab2e47eb2fd521fc3fdb2a5e156467340a17be91debbc75786367761cf60"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.3.1+4/rr.v5.3.1.x86_64-linux-gnu-cxx03.tar.gz"
