[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e296eddc440f805738d7c3a3773905097bc1bed4"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "1afa89db1811aefc58ef4d0e6e796650b936bc5e5bee0a7eb7262e57bed3152f"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.5.0+2/rr.v5.5.0.x86_64-linux-gnu-cxx03.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c15b91caba48cf253fe8f6dbdafbe18446c849c1"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "5169b4d22cb451ae61bad630af59e0136fc7dff2231ffb4394f4105a1b0b87d6"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.5.0+2/rr.v5.5.0.x86_64-linux-gnu-cxx11.tar.gz"
