[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "75e89875d7cbca47f5b30ac9ee1c50969ae8f717"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "f57a3f077e4455c9d3eb99c390a76028ec13b8fd544f80461bbeab045b72c5e6"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.4.1+15/rr.v5.4.1.x86_64-linux-gnu-cxx03.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b4d25eb5d440987b9777d85f1200cd692c3fc45"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "a208c8bdcd7d7d6168aec00be1f5fe20a65e81faa7e86612e6493c7fa052a4c2"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.4.1+15/rr.v5.4.1.x86_64-linux-gnu-cxx11.tar.gz"
