[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "736332586099f8a3e2225d5c821134ad123d7d0b"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "fcc1302d67111c721feae9692def7b08c97e0fcce70f203d6edc3abba46be623"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.4.1+7/rr.v5.4.1.x86_64-linux-gnu-cxx03.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57fac55d493334926a483bd285a862dfbe7ec80b"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "2b07364fe95a242098839c127c558a850ab08aa202da405377354b67a32eb2ac"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.4.1+7/rr.v5.4.1.x86_64-linux-gnu-cxx11.tar.gz"
