[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7ad628d1881858f9139e218c6d6e341908d6d75"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "28385f8dade4d93bc6b4fb742ac63ace6c19127f14a0861b42c6ad680dd82d63"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.4.1+0/rr.v5.4.1.x86_64-linux-gnu-cxx03.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dcd9da61fa2fba489cc59ac508125af91ad7740"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "fbb37c2cded0420cffec179a2c911297ce3aa928ea84d3d531c36182e7c60b26"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.4.1+0/rr.v5.4.1.x86_64-linux-gnu-cxx11.tar.gz"
