[[rr]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91c6e5e45354a377de104090ec1f5d366fdd9fea"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "e588d9dc22fb5fba4acc9ea7b110c61159acd9ae0f388f1c4da14c1774907e2a"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.6.0+2/rr.v5.6.0.aarch64-linux-gnu-cxx03.tar.gz"
[[rr]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4dc53bd08eb8aa502453fd2aa65f4e8956c1206"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "24d867f1c7f232f14d9fbb14cc88f8338d2633477caa71ed615e54611b6d19fd"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.6.0+2/rr.v5.6.0.aarch64-linux-gnu-cxx11.tar.gz"
[[rr]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31cf022c5f932c2ac4f5fdade4a7cbeb83cd22fb"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "295aed50ed47f1c931034b6b02b95819a1e9a98aeb4b4dbd5fad405838c83969"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.6.0+2/rr.v5.6.0.i686-linux-gnu-cxx03.tar.gz"
[[rr]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "110e83f3bbb4a5ad1590065e3498f396a726924e"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "c84dcb25175eb70165239f1c54432183d1e33adc94038370fee9a324f1ebc5c2"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.6.0+2/rr.v5.6.0.i686-linux-gnu-cxx11.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3c7c4146cbe41d078732d6745a40f539507f630"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "ac22ebd76252f4587f305901322fe552cda2ad132f15b15d9d43998c15b77d91"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.6.0+2/rr.v5.6.0.x86_64-linux-gnu-cxx03.tar.gz"
[[rr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f299f3a4a1e805597a0447a73ff3d5eaa81290f7"
libc = "glibc"
os = "linux"

    [[rr.download]]
    sha256 = "f0637288781d77435e0f4e7dbbb4a5dca890869674d8f00a2cc5d1002f7d77d5"
    url = "https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.6.0+2/rr.v5.6.0.x86_64-linux-gnu-cxx11.tar.gz"
