# Autogenerated wrapper script for rr_jll for x86_64-linux-gnu-cxx11
export rr

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("rr")
JLLWrappers.@declare_executable_product(rr)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        rr,
        "bin/rr",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
